all:
	gcc exercise1-1.c -o exercise1-1.o
	gcc exercise1-2.c -o exercise1-2.o
	gcc exercise1-3.c -o exercise1-3.o
	gcc exercise1-4.c -o exercise1-4.o
	gcc exercise1-5.c -o exercise1-5.o
	gcc exercise1-6.c -o exercise1-6.o
	gcc exercise1-7.c -o exercise1-7.o
	gcc exercise1-8.c -o exercise1-8.o
	gcc exercise1-9.c -o exercise1-9.o
	gcc exercise1-10.c -o exercise1-10.o

1:
	gcc exercise1-1.c -o exercise1-1.o
	./exercise1-1.o

2:
	gcc exercise1-2.c -o exercise1-2.o
	./exercise1-2.o

3:
	gcc exercise1-3.c -o exercise1-3.o
	./exercise1-3.o

4:
	gcc exercise1-4.c -o exercise1-4.o
	./exercise1-4.o

5:
	gcc exercise1-5.c -o exercise1-5.o
	./exercise1-5.o

6:
	gcc exercise1-6.c -o exercise1-6.o
	./exercise1-6.o

7:
	gcc exercise1-7.c -o exercise1-7.o
	./exercise1-7.o

8:
	gcc exercise1-8.c -o exercise1-8.o
	cat testfiles/testfile.txt | ./exercise1-8.o

9:
	gcc exercise1-9.c -o exercise1-9.o
	cat testfiles/testfile2.txt | ./exercise1-9.o

10:
	gcc exercise1-10.c -o exercise1-10.o
	cat testfiles/testfile3.txt | ./exercise1-10.o

clean:
	rm *.o*

clear:
	rm *.o*
